language: node_js
node_js:
 - "6"
 - "4"
 - "0.12"
script: "npm run-script coverage"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

after_success:
  - bash <(curl -s https://codecov.io/bash)

